import { Injectable } from '@angular/core';

export interface Message {
  id: number;
  fromName: string;
  subject: string;
  descripcion: string;
  variante?: string;
  positivo1?: string;
  positivo2?: string;
  positivo3?: string;
  negativo1?: string;
  negativo2?: string;
  negativo3?: string;
  imagen?: string;
  imagen2?: string;
  read: boolean;
}

@Injectable({
  providedIn: 'root',
})
export class DataService {
  public messages: Message[] = [
    // 10
    {
      id: 0,
      fromName: '1. La unión de la Abeja 🐝',
      subject: 'La unión de la Abeja',
      descripcion:
        'La mujer se sienta sobre el pene de su pareja, el mismo sentado y las piernas desplegadas hacia adelante. La mujer puede entonces ir y venir verticalmente apoyándose sobre las manos y las piernas. El hombre acompaña al movimiento levantándola por las nalgas o los muslos.',
      variante:
        'El hombre puede posicionarse de espaldas a la pared para un mejor apoyo. La mujer puede arrodillarse en vez de sentarse para poder agacharse más fácilmente hacia adelante y cambiar de ángulo de inclinación de la vagina.',
      positivo1: '– La mujer controla mejor la profundidad de la penetración que en las demás posiciones con penetración por detrás',
      positivo2: '– Las paredes de delante de la vagina y el punto G están bien estimulados',
      positivo3: '– El hombre en posición pasiva puede acariciar prolongadamente los senos y el clítoris de su pareja.',
      negativo1:'– La posición puede resultar molesta para el hombre en ausencia de apoyo.',
      imagen: '../../assets/images/1. La union de la abeja.png',
      read: false,
    },
    {
      id: 1,
      fromName: '2. La unión del Aguila 🦅',
      subject: 'La unión del Aguila',
      descripcion: 'Tumbados sobre el costado, la pareja se abraza con los brazos y las piernas, la mujer apretando la cadera de su pareja entre sus piernas. El hombre repliega ligeramente sus piernas para facilitar la penetración',
      positivo1: '– Posición muy intima ofreciendo un contacto máximo entre la pareja',
      positivo2: '– Buena profundidad de penetración si el hombre pliega suficientemente sus muslos entre los de su pareja.',
      negativo1: '– Amplitud de movimiento limitado.',
      imagen: '../../assets/images/2. La union del aguila.png',
      read: false,
    },
    {
      id: 2,
      fromName: '3. La posición de la «Alineación Perfecta» 🅿️',
      subject: 'La alineación perfecta',
      descripcion: 'La mujer se tumba sobre el hombre las piernas abiertas para facilitar la penetración. Una vez el pene bien asentado, ella aprieta las piernas para que los cuerpos de la pareja se superpongan en un alineación perfecta. La mujer puede entonces empezar la estimulación frotando su cuerpo lateralmente y horizontalmente contra el de su pareja.',
      positivo1: '– Posición muy intima ofreciendo un contacto máximo entre la pareja.',
      positivo2: '– Las paredes vaginales más apretadas favorecen sensaciones más intensas.',
      positivo3: '– Recomendado para el amor tántrico.',
      negativo1: '– Profundidad de penetración y amplitudes de movimiento limitadas.',
      imagen: '../../assets/images/3. La alineacion perfecta.png',
      read: false,
    },
    {
      id: 3,
      fromName: '4. La unión de los amantes 🅰️',
      subject: 'La unión de los amantes',
      descripcion: 'La pareja de pie cara a cara, el hombre frota su pene sobre la vulva de su pareja. Después de varios minutos de fricción, la vulva se abrirá naturalmente para permitir una penetración superficial. Si la mujer es de más pequeña estatura que el hombre, ella podrá agrandarse llevando zapatos de tacones de agujas o agrandándose artificialmente con un soporte (tal como una guía de teléfono) debajo de cada pie.',
      positivo1: '– Posición práctica realizable al imprevisto en todas las situaciones',
      positivo2: '– Buena estimulación del clítoris y del glande.',
      negativo1: '– Penetración superficial.',
      negativo2: '– Posición difícilmente realizable si la pareja es de estatura muy diferente.',
      imagen: '../../assets/images/4. La union de los amantes.png',
      read: false,
    },
    {
      id: 4,
      fromName: '5. La posición del Amazona 🌱',
      subject: 'Amazona',
      descripcion: 'El hombre está sentado sobre una silla. La mujer se sienta en amazona sobre uno de los muslos de su pareja y guía al pene hasta la apertura de la vagina. Una vez el pene introducido, ella podrá contraer sus músculos vaginales para guardar la penetración, y evitar les salidas inapropiadas.',
      positivo1: '– El hombre puede fácilmente acariciar los senos y el clítoris de su pareja para llevarla más fácilmente al orgasmo.',
      positivo2: '– Posición recomendada a los hombres que sufren de eyaculación precoz',
      negativo1: '– Amplitud de movimiento limitada y penetración poco profunda.',
      imagen: '../../assets/images/5. Amazona.png',
      read: false,
    },
    {
      id: 5,
      fromName: '6. La posición de Andromaca 👩🏻',
      subject: 'Andromaca',
      descripcion: 'El hombre está tumbado sobre la espalda, su pareja se posiciona encima de él, en cuclillas o arrodillada, el busto completamente erguido. Ella controla perfectamente la profundidad y el ritmo de la penetración y puede liberar a sus anchas sus fantasías de dominación.',
      positivo1: '– La mujer guarda un control total permitiéndole estar más en confianza y encontrar los correctos movimientos para maximizar su placer.',
      positivo2: '– El hombre tiene las manos libres para proporcionar todavía más placer a su pareja acariciando sus senos, sus nalgas o su clítoris.',
      positivo3: '– Posición ofreciendo una buena estimulación del punto G.',
      negativo1: '– Ángulo de penetración a veces incómodo para el hombre, hasta doloroso si la verga se dobla.',
      imagen: '../../assets/images/6. Andromaca.png',
      read: false,
    },
    {
      id: 6,
      fromName: '7. La unión del Antílope 🦌',
      subject: 'La unión del Antílope ',
      descripcion: 'De rodillas sobre el suelo, la mujer se yergue tomando apoyo contra el borde de la cama. El hombre la penetra por detrás, erguido sobre las rodillas.',
      variante: 'la mujer puede, o guardar sus piernas abiertas, colocándolas por ambas partes de las de su pareja para ofrecer una apertura vaginal máxima, o cerrar sus muslos uno contra el otro para comprimir la vagina y así apretar la verga.',
      positivo1: '– Buena estimulación de las paredes frontales de la vagina y del punto G.',
      positivo2: '– Posibilidad para el hombre de estimular el clítoris y los senos de su pareja',
      positivo3: '– La mujer puede fantasear más fácilmente sobre parejas imaginarias.',
      negativo1: '– Cuidado con los rasguños de las rodillas.',
      imagen: '../../assets/images/7. La union del antilope.png',
      read: false,
    },
    {
      id: 7,
      fromName: '8. La postura del Arbol a Fruta 🌳🍐',
      subject: 'Arbol a Fruta',
      descripcion: 'Una variante de la posición del Indra proporcionando sensaciones similares disminuyendo la sensación de aplastamiento ejercido por el hombre sobre su pareja. La mujer guarda una pierna sobre el busto del hombre y libera la otra desplegándola sobre el costado.',
      positivo1: '– Penetración profunda.',
      positivo2: '– Fuerte estimulación gracias a la compresión del vientre y de la vagina.',
      negativo1: '– Potencialmente doloroso si el pene toca el fondo de la vagina.',
      imagen: '../../assets/images/8. Arbol a fruta.png',
      read: false,
    },
    {
      id: 8,
      fromName: '9. La postura de la Balanza ⚖️',
      subject: 'La Balanza',
      descripcion: 'El hombre está sentado sobre el borde de la cama o sobre una silla. La mujer le da la espalda antes de sentarse sobre sus muslos. Una vez el pene en ella, ella puede entonces agacharse hacia adelante para llegar a una posición de equilibrio y balancearse a lo largo del pene. Para estabilizar la posición, la mujer cogerá apoyo sobre las rodillas del hombre que la sostendrá por los senos.',
      positivo1: '– Posición permitiendo una penetración bastante profunda y una buena amplitud de movimiento vertical.',
      positivo2: '– El hombre puede fácilmente acariciar los senos y el clítoris de su pareja para llevarla más fácilmente al orgasmo.',
      negativo1: '– Posición de equilibrio difícil de dominar.',
      imagen: '../../assets/images/9. La balanza.png',
      read: false,
    },
    {
      id: 9,
      fromName: '10. La postura del Columpio 🪑',
      subject: 'El Columpio',
      descripcion: 'La mujer da la espalda a su pareja y puede según su deseo sentarse sobre él, los pies sirviendo de apoyo, o bien arrodillarse por ambas partes de las caderas de su pareja, esta última posición favoreciendo una más gran amplitud de estimulación.',
      positivo1: '– Posición ofreciendo al hombre un ángulo de vista excepcional sobre la penetración y un panorama muy excitante sobre las nalgas y el sexo de su pareja.',
      positivo2: '– Autoriza una gran amplitud de movimiento (particularmente en la versión arrodillada) para aportar un placer máximo al hombre y llevarle deprisa al orgasmo.',
      positivo3: '– Permite fantasear más fácilmente a la mujer sobre parejas imaginarias.',
      negativo1: '– El ángulo de penetración puede ser incómodo para algunos hombres.',
      imagen: '../../assets/images/10. El columpio.png',
      read: false,
    },

    // 11
    {
      id: 10,
      fromName: '11. La postura del Bambú 🪴',
      subject: 'El Bambú',
      descripcion: 'A partir de la posición del misionero, la mujer desliza una pierna sobre el hombro de su pareja que echa simultáneamente su rodilla hacia delante. Después de varios instantes en esta posición, la mujer baja su pierna y repite el mismo movimiento con la otra pierna. Cada movimiento debe ser repetido varias veces.',
      positivo1: '– Posición graciosa, original y bastante acrobática para las parejas las más atrevidas.',
      negativo1: '– Estimulación limitada.',
      negativo2: '– Exige una buena agilidad de la mujer.',
      imagen: '../../assets/images/11. El bambu.png',
      read: false,
    },
    {
      id: 11,
      fromName: '12. La unión de la Boa 🐍',
      subject: 'La unión de la Boa',
      descripcion: 'La mujer tumbada sobre la espalda, ligeramente sobre el costado, apoya sus piernas sobre la cadera de su pareja. El hombre puede entonces guiar su pene para penetrarla con suavidad. Ella deberá entonces comprimir los muslos para conservar el pene bien asentado y maximizar les sensaciones.',
      positivo1: '– Una posición original para hacer el amor con suavidad, sin prisas.',
      positivo2: '– Recomendado para el amor tántrico.',
      negativo1: '– Amplitud y profundidad de movimiento limitadas.',
      negativo2: '– Riesgos de salida involuntaria si el pene no esta correctamente apretado.',
      imagen: '../../assets/images/12. La union de la boa.png',
      read: false,
    },
    {
      id: 12,
      fromName: '13. La postura de la Carretilla 🛞',
      subject: 'La Carretilla',
      descripcion: 'Tumbada sobre la espalda, la mujer lleva sus nalgas sobre el borde de la cama y aprieta con sus piernas la cintura de su pareja. El hombre se arrodilla sobre el suelo para penetrarla guardando la verga horizontal, paralela al eje de la vagina',
      variante: 'El hombre puede estar de pie mientras la mujer se tumbará sobre un escritorio o una mesa.',
      positivo1: '– La alineación horizontal de la verga y de la vagina proporciona sensaciones diferentes de las proporcionadas cuando la penetración se hace desde arriba hacia abajo',
      positivo2: '– Penetración profunda proporcionando una buena estimulación de las paredes de la vagina.',
      positivo3: '– Posición excitante, particularmente para la variante practicada de pie.',
      negativo1: '– El confort y la factibilidad de esta posición dependen en gran parte de la altura de la cama o de la de la mesa.',
      imagen: '../../assets/images/13. La carretilla.png',
      read: false,
    },
    {
      id: 13,
      fromName: '14. La unión del Gato 🐈',
      subject: 'La unión del Gato',
      descripcion: 'A partir de la posición del misionero o de la de la monta, la pareja bascula sobre el costado y con suavidad para evitar una salida inopinada del pene.',
      positivo1: '– Posición intima y dulce permitiendo a la pareja mirarse y abrazarse sin que uno se sienta dominado por el otro.',
      negativo1: '– Profundidad de penetración y amplitud de y movimiento limitadas.',
      negativo2: '– Riesgos de salida involuntaria durante el balanceo.',
      imagen: '../../assets/images/14. La union del gato.png',
      read: false,
    },
    {
      id: 14,
      fromName: '15. La posición de la Monta Ⓜ️',
      subject: 'La Monta',
      descripcion: 'El hombre se tumba sobre la espalda mientras su pareja se arrodilla encima de él y abraza sus muslos con los suyos. Ella controla la amplitud del movimiento vertical y horizontal para maximizar las sensaciones sobre su clítoris y sus paredes vaginales o para llevar deprisa el hombre al orgasmo.',
      positivo1: '– La mujer esta más libre y más activa: ella escoge el ritmo, la velocidad y el tipo de movimiento.',
      positivo2: '– El hombre, quedando pasivo, puede concentrarse sobre les sensaciones y el placer acariciando la espalda de su pareja.',
      negativo1: '– Posición con un poco de falta de originalidad, pase entonces a otra cosa después de varios minutos de estimulación.      ',
      imagen: '../../assets/images/15. La monta.png',
      read: false,
    },
    {
      id: 15,
      fromName: '16. La postura de las Tijeras ✂️',
      subject: 'Las Tijeras',
      descripcion: 'A partir de la posición de Andromaca, la mujer bascula hacia atrás hasta los pies de su pareja. Esta posición esta recomendada para retrasar la eyaculación.',
      positivo1: '– Permite una muy buena estimulación manual del clítoris.',
      positivo2: '– Vista excitante para el hombre.',
      positivo3: '– Buena posición para retrasar el orgasmo masculino.',
      negativo1: '– Exige una muy buena agilidad de la mujer.',
      imagen: '../../assets/images/16. Las tijeras.png',
      read: false,
    },
    {
      id: 16,
      fromName: '17. La posición de la Cortesana 👑',
      subject: 'La Cortesana',
      descripcion: 'El hombre esta arrodillado sobre el suelo y penetra su pareja sentada sobre el borde de la cama o sobre una silla. Ella puede entonces estrechar sus piernas alrededor de la cintura de su pareja.',
      variante: 'La mujer esta tumbada sobre una mesa o un escritorio, mientras el hombre la penetra de pie.',
      positivo1: '– Posición cómoda y poco cansina para la pareja.',
      positivo2: '– Buena profundidad de penetración y amplitud de movimientos de la pelvis.',
      positivo3: '– Práctica en la oficina, especialmente en la versión de pie.',
      negativo1: '– La factibilidad de la posición depende en gran parte de la altura del soporte sobre el cual se apoya la mujer.',
      imagen: '../../assets/images/17. La cortesana.png',
      read: false,
    },
    {
      id: 17,
      fromName: '18. La unión del Cangrejo 🦀',
      subject: 'La unión del Cangrejo',
      descripcion: 'La mujer monta de espalda su pareja, acostada sobre la cama. Ella guía al pene en la vagina y entonces bascula hacia atrás tomando apoyo sobre sus brazos. Ella puede entonces ir y venir verticalmente accionando sus piernas.',
      positivo1: '– La mujer controla la profundidad y la velocidad de la penetración.',
      positivo2: '– El hombre puede libremente acariciar los senos de su pareja.',
      positivo3: '– La sensación del cabello de la mujer acariciando la cara del hombre es especialmente agradable y excitante.',
      negativo1: '– Riesgos de salida involuntaria en caso de movimientos demasiado rápidos e incontrolados.',
      imagen: '../../assets/images/18. La union del cangrejo.png',
      read: false,
    },
    {
      id: 18,
      fromName: '19. La postura de las Cucharas 🥄',
      subject: 'Las Cucharas',
      descripcion: 'La mujer se tumba sobre el costado las piernas plegadas en posición acurrucada. El hombre se posiciona detrás y esposa los contornos del cuerpo de su pareja para penetrarla. Puede entonces fácilmente acariciar sus senos y su clítoris besándola en la nuca y detrás de las orejas.',
      positivo1: '– Posición dulce y descansada favoreciendo les caricias y la intimidad de la pareja.',
      positivo2: '– La mujer puede fácilmente masturbarse o guiar la mano de su pareja para llegar más deprisa el orgasmo.',
      negativo1: '– Amplitud de los movimientos de la pelvis limitada.',
      imagen: '../../assets/images/19. Las cucharas 1.png',
      imagen2: '../../assets/images/19. Las cucharas 2.png',
      read: false,
    },
    {
      id: 19,
      fromName: '20. La posición de la Danza del Misionero 🙆🏻‍♂️',
      subject: 'La Danza del Misionero',
      descripcion: 'A partir de la posición del misionero, la mujer aprieta les nalgas y comba su cadera y entonces ondula su cintura en un movimiento circular lateral y vertical.',
      positivo1: '– Muy buena estimulación favoreciendo un desencadenamiento rápido del orgasmo para el hombre.',
      negativo1: '– Posición difícil de mantener mucho tiempo porqué es fatigante para la pareja.',
      imagen: '../../assets/images/20. La danza del misionero.png',
      read: false,
    },

    // 21
    {
      id: 20,
      fromName: '21. La union de la diosa 👩🏻‍🦳',
      subject: 'La union de la Diosa',
      descripcion: 'El hombre está sentado sobre la cama, eventualmente la espalda contra la pared para un mejor apoyo. La mujer se sienta sobre su pene guiándole hacia la vagina y entonces aprieta la cintura de su pareja con las piernas. Ella puede entonces ondular de la pelvis para estimular bien el clítoris y las paredes vaginales.',
      positivo1: '– Posición intima permitiendo a la pareja abrazarse y al hombre lamer los senos de su pareja.',
      positivo2: '– Penetración profunda ofreciendo también una buena estimulación del clítoris.',
      positivo3: '– Recomendado para retrasar el orgasmo para los hombres que sufren de eyaculación precoz.',
      negativo1: '– Estimulación limitada para el hombre.',
      imagen: '../../assets/images/21. La union de la diosa.png',
      read: false,
    },
    {
      id: 21,
      fromName: '22. La unión del Elefante 🐘',
      subject: 'La unión del Elefante',
      descripcion: 'A partir de la posición en galga, la mujer se desploma despacio para que el hombre la recubra íntegramente. La mujer puede dejar sus piernas abiertas para facilitar la penetración o bien apretar sus muslos uno contra el otro para apretar de manera más firme la verga en la vagina.',
      variante: 'El hombre puede enderezarse sobre sus antebrazos para aliviar un poco su pareja y penetrarla más vigorosamente.',
      positivo1: '– Muy buena estimulación de las paredes frontales de la vagina y del punto G.',
      positivo2: '– El hombre puede simultáneamente deslizar su mano bajo el vientre de su pareja para estimular su clítoris.',
      positivo3: '– Contacto físico máximo entre la pareja.',
      negativo1: '– Libertad de movimiento casi nula para la mujer que puede sentirse aplastada por su pareja.',
      imagen: '../../assets/images/22. La union del elefante 1.png',
      imagen2: '../../assets/images/22. La union del elefante 2.png',
      read: false,
    },
    {
      id: 22,
      fromName: '23. La unión del Emu 🦬',
      subject: 'La unión del Emu',
      descripcion: 'La pareja de pie, la mujer da la espalda a su pareja. El hombre la atrae contra él y la penetra por detrás. Agachándose hacia adelante, la mujer modifica el ángulo de la penetración y la hace que sea más profunda.',
      variante: 'a mujer puede tomar apoyo sobre una pared o un ventanal, o apoyar su busto sobre una mesa o un escritorio. Ella podrá entonces totalmente abandonarse y el hombre podrá penetrarla más vigorosamente.',
      positivo1: '– Posición muy excitante permitiendo al hombre realizar sus fantasías de dominación y a la mujer fantasear más fácilmente sobre parejas imaginarias.',
      positivo2: '– Penetración profunda proporcionando una muy buena estimulación de las paredes frontales de la vagina y del punto G.',
      positivo3: '– El hombre puede simultáneamente acariciar el clítoris o los senos de su pareja.',
      negativo1: '– Posición difícil si la pareja es de estatura muy diferente. El hombre deberá entonces flexionar las piernas o agrandarse sobre un soporte para que la posición sea más agradable.',
      imagen: '../../assets/images/23. La union del emu 1.png',
      imagen2: '../../assets/images/23. La union del emu 2.png',
      read: false,
    },
    {
      id: 23,
      fromName: '24. La postura del Yunque ⚒️',
      subject: 'El Yunque',
      descripcion: 'Tumbada sobre la espalda, la mujer viene posicionar sus pies sobre los hombros de su pareja. Esta posición favorece una penetración muy profunda. Eviten pues de practicarla justo después de los prelimininarios porqué la vagina no habrá alcanzado su estatura máxima y podría no estar suficientemente lubrificada',
      positivo1: '– Permite una penetración máxima.',
      positivo2: '– Proporciona sensaciones muy intensas a la mujer, especialmente si el hombre eyacula en esta posición.',
      positivo3: '– Permite al hombre realizar sus fantasías de dominación.',
      negativo1: '– Posición necesitando una muy buena agilidad de la mujer.',
      negativo2: '– Potencialmente doloroso para la mujer si el pene toca el fondo de la vagina o sí la vagina esta insuficientemente lubrificada.',
      imagen: '../../assets/images/24. El yunque.png',
      read: false,
    },
    {
      id: 24,
      fromName: '25. La postura de la Estrella 🌟',
      subject: 'La Estrella',
      descripcion: 'La mujer tumbada sobre la espalda abre de forma amplia las piernas, el hombre posiciona una pierna entre las de la mujer y la penetra de costado, tomando apoyo sobre su brazo opuesto. Puede aumentar la estimulación frotando su muslo contra el clítoris.',
      positivo1: '– La penetración por el costado proporciona sensaciones diferentes para la mujer como para el hombre.',
      positivo2: '– La vulva y el clítoris están bien estimulados por los roces del muslo del hombre.',
      positivo3: '– La pareja tiene cada uno una mano libre para acariciarse y abrazarse.',
      negativo1: '– Movimientos de la pelvis limitados.',
      imagen: '../../assets/images/25. La estrella.png',
      read: false,
    },
    {
      id: 25,
      fromName: '26. La posición de la Gran Apertura 🔓',
      subject: 'La Gran Apertura',
      descripcion: 'A partir de la posición de Andromaca, la mujer bascula la espalda hacia atrás y desliza una pierna bajo la de su pareja. En el transcurso de la maniobra, ella tendrá cuidado en sostener el pene bien apretado en su vagina para evitar cualquier salida involuntaria. Ella podrá entonces ir y venir de forma transversal de izquierda a derecha para experimentar sensaciones nuevas.',
      positivo1: '– Una posición original que resulta ser cómoda para la pareja.',
      positivo2: '– La penetración transversal ofrece sensaciones diferentes especialmente estimulando les paredes laterales de la vagina.',
      negativo1: '– Riesgo de salida involuntaria durante el balanceo.',
      negativo2: '– Amplitud de movimiento un poco limitada.',
      imagen: '../../assets/images/26. La gran apertura.png',
      read: false,
    },
    {
      id: 26,
      fromName: '27. La unión de la Rana 🐸',
      subject: 'La unión de la Rana',
      descripcion: 'El hombre esta acostado sobre la espalda, las piernas entreabiertas. La mujer se tumba sobre él de manera que la planta de sus pies haga apoyo sobre la parte superior de los pies de su pareja. Ella puede entonces utilizar este apoyo para mover su cuerpo de adelante hacia atrás. El hombre puede simultáneamente estabilizar la posición y acompañar el movimiento cogiendo su pareja por la cintura.',
      positivo1: '– Posición original y graciosa.',
      positivo2: '– Favorece la estimulación del clítoris frotando sobre la pelvis del hombre.',
      negativo1: '– Libertad de movimiento y amplitud bastante limitadas.',
      imagen: '../../assets/images/27. La union de la rana.png',
      read: false,
    },
    {
      id: 27,
      fromName: '28. La unión de la Ostra 🦪',
      subject: 'La unión de la Ostra',
      descripcion: 'Tumbada sobre la espalda, la mujer repliega sus muslos contra su vientre. El hombre la sujeta por las rodillas y utiliza los muslos de su pareja como un soporte para facilitar le movimiento de vaivén y conservar un ritmo regular.',
      positivo1: '– Penetración profunda y buena amplitud de los movimientos.',
      positivo2: '– Buena estimulación para la pareja porqué la vagina se comprime sobre el pene.',
      negativo1: '– Potencialmente doloroso para la mujer si la penetración es demasiado profunda o demasiado violenta.',
      imagen: '../../assets/images/28. La union de la ostra.png',
      read: false,
    },
    {
      id: 28,
      fromName: '29. La posición de la Indra 🙇🏻',
      subject: 'La Indra',
      descripcion: 'El hombre se yergue sobre sus rodillas, la mujer tumbada sobre la espalda echa sus pies contra el busto de su pareja. El hombre se inclina hacia adelante para comprimir los muslos de la mujer contra sus senos.',
      positivo1: '– Penetración máxima y muy profunda.',
      positivo2: '– Fuerte estimulación gracias a la compresión del vientre y de la vagina.',
      negativo1: '– Potencialmente doloroso si el pene toca el fondo de la vagina.',
      imagen: '../../assets/images/29. La indra.png',
      read: false,
    },
    {
      id: 29,
      fromName: '30. La posición del Loto 💮',
      subject: 'El Loto',
      descripcion: 'Tumbada sobre la espalda, la mujer pliega sus piernas en posición del Loto mostrando de esta manera su vagina de forma amplia abierta a su pareja.',
      positivo1: '– Posición graciosa y original.',
      negativo1: '– Requiere una buena agilidad.',
      negativo2: '– Posición difícil de mantener mucho tiempo y a veces dolorosa para la mujer.',
      imagen: '../../assets/images/30. El loto.png',
      read: false,
    },

    // 31
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },

    // 41
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },
    // {
    //   id: 19,
    //   fromName: '20. ',
    //   subject: '',
    //   descripcion: '',
    //   positivo1: '',
    //   negativo1: '',
    //   imagen: '../../assets/images/20. L.png',
    //   read: false,
    // },

    // 51
    // {
    //   fromName: '#51 Postura 51',
    //   subject: 'Postura 51',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#52 Postura 52',
    //   subject: 'Postura 52',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#53 Postura 53',
    //   subject: 'Postura 53',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#54 Postura 54',
    //   subject: 'Postura 54',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#55 Postura 55',
    //   subject: 'Postura 55',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#56 Postura 56',
    //   subject: 'Postura 56',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#57 Postura 57',
    //   subject: 'Postura 57',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#58 Postura 58',
    //   subject: 'Postura 58',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#59 Postura 59',
    //   subject: 'Postura 59',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#60 Postura 60',
    //   subject: 'Postura 60',
    //   id: 0,
    //   read: false,
    // },

    // 61
    // {
    //   fromName: '#61 Postura 61',
    //   subject: 'Postura 61',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#62 Postura 62',
    //   subject: 'Postura 62',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#63 Postura 63',
    //   subject: 'Postura 63',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#64 Postura 64',
    //   subject: 'Postura 64',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#65 Postura 65',
    //   subject: 'Postura 65',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#66 Postura 66',
    //   subject: 'Postura 66',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#67 Postura 67',
    //   subject: 'Postura 67',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#68 Postura 68',
    //   subject: 'Postura 68',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#69 Postura 69',
    //   subject: 'Postura 69',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#70 Postura 70',
    //   subject: 'Postura 70',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },

    // 71
    // {
    //   fromName: '#71 Postura 71',
    //   subject: 'Postura 71',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#72 Postura 72',
    //   subject: 'Postura 72',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#73 Postura 73',
    //   subject: 'Postura 73',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#74 Postura 74',
    //   subject: 'Postura 74',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#75 Postura 75',
    //   subject: 'Postura 75',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#76 Postura 76',
    //   subject: 'Postura 76',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#77 Postura 77',
    //   subject: 'Postura 77',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#78 Postura 78',
    //   subject: 'Postura 78',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#79 Postura 79',
    //   subject: 'Postura 79',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#80 Postura 80',
    //   subject: 'Postura 60',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },

    // 81
    // {
    //   fromName: '#81 Postura 81',
    //   subject: 'Postura 81',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#82 Postura 82',
    //   subject: 'Postura 82',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#83 Postura 83',
    //   subject: 'Postura 83',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#84 Postura 84',
    //   subject: 'Postura 84',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#85 Postura 85',
    //   subject: 'Postura 85',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#86 Postura 86',
    //   subject: 'Postura 86',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#87 Postura 87',
    //   subject: 'Postura 87',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#88 Postura 88',
    //   subject: 'Postura 88',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#89 Postura 89',
    //   subject: 'Postura 89',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#90 Postura 90',
    //   subject: 'Postura 90',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },

    // 91
    // {
    //   fromName: '#91 Postura 91',
    //   subject: 'Postura 91',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#92 Postura 92',
    //   subject: 'Postura 92',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#93 Postura 93',
    //   subject: 'Postura 93',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#94 Postura 94',
    //   subject: 'Postura 94',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#95 Postura 95',
    //   subject: 'Postura 95',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#96 Postura 96',
    //   subject: 'Postura 96',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#97 Postura 97',
    //   subject: 'Postura 97',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#98 Postura 98',
    //   subject: 'Postura 98',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#99 Postura 99',
    //   subject: 'Postura 99',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
    // {
    //   fromName: '#100 Postura 100',
    //   subject: 'Postura 100',
    //   date: 'Botones de accion',
    //   id: 0,
    //   read: false,
    // },
  ];

  constructor() {}

  public getMessages(): Message[] {
    return this.messages;
  }

  public getMessageById(id: number): Message {
    return this.messages[id];
  }
}
